### ISSUE TITLE
pairing issues

### ISSUE THREAD

**Issue by acuadulza** [andyb2000/HACS-husqvarna_automower_ble#26]
I am trying to integrate my two Husqvarna Automower 305 units with Home Assistant, but I am encountering difficulties. After numerous attempts, occasionally one of them pairs successfully, but shortly after, I receive the message: "Failed setup, will retry: couldn't find device."

I have a doubt  regarding the setup: I am using three ESP32 BLE proxies (one of them dedicated to the Automowers) alongside the built-in BLE on my HASS miniPC. How can I determine which proxy my Automowers are connecting to if the recommended ESPHome setup in the integration does not specify this?

**HASS Versions:**
Core: 2024.10.3
Supervisor: 2024.10.2
Operating System: 13.2

**ESPhome configuration**

```
esphome:
  name: mower-ble

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

ota:
  platform: esphome

api:
  encryption:
    key: iyZLwoyD7DIrMllHngI2JbbtRqd3xVmH+zjzZes5Bkk

wifi:
  ssid: "xxxxxxxx"
  password: "xxxxxxxxx"
  manual_ip:
    static_ip: 192.168.0.33
    gateway: 192.168.0.1
    subnet: 255.255.255.0   

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: '*'
        then:
          esp32_ble_tracker.start_scan:

button:
  - platform: restart
    name: "Mower ESP Restart"

bluetooth_proxy:
  active: true
  cache_services: true`
```
